import type { Marca, Producto, GaleriaItem, Sugerencia, Pedido } from '@/types'

export const MARCAS: Marca[] = [
  {
    id: 'm1',
    nombre: 'Charlotte Tilbury',
    slug: 'charlotte-tilbury',
    logo_url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=200&h=200&fit=crop',
    descripcion: 'Marca británica de lujo fundada por la maquilladora Charlotte Tilbury. Conocida por su enfoque en realzar la belleza natural con fórmulas innovadoras.',
    pais_origen: 'Reino Unido',
    rango_precio: '$80.000 - $350.000 COP',
    popularidad_pct: 92,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'm2',
    nombre: 'NARS',
    slug: 'nars',
    logo_url: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=200&h=200&fit=crop',
    descripcion: 'Marca de cosméticos de alta gama fundada por el fotógrafo y maquillador François Nars. Reconocida por sus pigmentos intensos y packaging icónico.',
    pais_origen: 'Estados Unidos',
    rango_precio: '$70.000 - $280.000 COP',
    popularidad_pct: 88,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'm3',
    nombre: 'MAC',
    slug: 'mac',
    logo_url: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=200&h=200&fit=crop',
    descripcion: 'Make-up Art Cosmetics, fundada en Toronto en 1984. Favorita de maquilladores profesionales y amantes del maquillaje en todo el mundo.',
    pais_origen: 'Canadá',
    rango_precio: '$50.000 - $220.000 COP',
    popularidad_pct: 85,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'm4',
    nombre: 'Fenty Beauty',
    slug: 'fenty-beauty',
    logo_url: 'https://images.unsplash.com/photo-1596704017234-0902573e2fa1?w=200&h=200&fit=crop',
    descripcion: 'Creada por Rihanna en 2017, revolucionó la industria con 40 tonos de base para todos los tipos de piel. Inclusividad como filosofía de marca.',
    pais_origen: 'Estados Unidos',
    rango_precio: '$65.000 - $250.000 COP',
    popularidad_pct: 90,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'm5',
    nombre: 'Dior Beauty',
    slug: 'dior-beauty',
    logo_url: 'https://images.unsplash.com/photo-1512207736890-6ffed8a84e8d?w=200&h=200&fit=crop',
    descripcion: 'La línea de cosméticos de la maison Christian Dior. Elegancia francesa y lujo incomparable en cada producto.',
    pais_origen: 'Francia',
    rango_precio: '$120.000 - $350.000 COP',
    popularidad_pct: 87,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'm6',
    nombre: 'YSL Beauty',
    slug: 'ysl-beauty',
    logo_url: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=200&h=200&fit=crop',
    descripcion: 'Yves Saint Laurent Beauty captura la audacia y sensualidad de la moda de alta costura en sus cosméticos de lujo.',
    pais_origen: 'Francia',
    rango_precio: '$110.000 - $320.000 COP',
    popularidad_pct: 84,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'm7',
    nombre: 'Rare Beauty',
    slug: 'rare-beauty',
    logo_url: 'https://images.unsplash.com/photo-1631214524020-3c69888fd1c8?w=200&h=200&fit=crop',
    descripcion: 'Fundada por Selena Gomez, Rare Beauty promueve la salud mental y la autoaceptación. Fórmulas ligeras que realzan tu belleza única.',
    pais_origen: 'Estados Unidos',
    rango_precio: '$55.000 - $180.000 COP',
    popularidad_pct: 89,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'm8',
    nombre: 'Huda Beauty',
    slug: 'huda-beauty',
    logo_url: 'https://images.unsplash.com/photo-1586495777744-4e6232bf4400?w=200&h=200&fit=crop',
    descripcion: 'Huda Kattan creó una de las marcas de cosméticos más influyentes de la última década. Glam máximo con pigmentos ultra-saturados.',
    pais_origen: 'Emiratos Árabes',
    rango_precio: '$60.000 - $300.000 COP',
    popularidad_pct: 86,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'm9',
    nombre: 'Maybelline',
    slug: 'maybelline',
    logo_url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=200&h=200&fit=crop',
    descripcion: 'Maybe she\'s born with it, maybe it\'s Maybelline. La marca de maquillaje accesible más icónica del mundo, disponible para todas.',
    pais_origen: 'Estados Unidos',
    rango_precio: '$25.000 - $95.000 COP',
    popularidad_pct: 78,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'm10',
    nombre: "L'Oréal Paris",
    slug: 'loreal-paris',
    logo_url: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=200&h=200&fit=crop',
    descripcion: 'Porque tú lo vales. L\'Oréal Paris combina ciencia de vanguardia con cosméticos accesibles para todas las mujeres del mundo.',
    pais_origen: 'Francia',
    rango_precio: '$30.000 - $120.000 COP',
    popularidad_pct: 80,
    created_at: '2024-01-01T00:00:00Z',
  },
]

export const PRODUCTOS: Producto[] = [
  // Charlotte Tilbury (m1)
  {
    id: 'p1',
    marca_id: 'm1',
    nombre: 'Matte Revolution Lipstick - Pillow Talk',
    descripcion: 'El labial más icónico de Charlotte Tilbury. Un rosa desnudo perfectamente equilibrado que favorece a todos los tonos de piel. Fórmula cremosa con vitamina E.',
    precio_cop: 165000,
    categoria: 'labios',
    imagen_url: 'https://images.unsplash.com/photo-1586495777744-4e6232bf4400?w=400&h=400&fit=crop',
    tono: 'Pillow Talk',
    acabado: 'Matte',
    duracion_horas: 8,
    ingredientes: ['Vitamina E', 'Aceite de jojoba', 'Cera de carnauba'],
    rating: 4.9,
    review_count: 2847,
    es_nuevo: false,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: 'p2',
    marca_id: 'm1',
    nombre: 'Beautiful Skin Foundation',
    descripcion: 'Base de cobertura buildable con acabado luminoso. Formulada con ácido hialurónico y péptidos para una piel radiante durante todo el día.',
    precio_cop: 285000,
    categoria: 'base',
    imagen_url: 'https://images.unsplash.com/photo-1512207736890-6ffed8a84e8d?w=400&h=400&fit=crop',
    tono: 'N4 Neutral',
    acabado: 'Luminoso',
    duracion_horas: 12,
    ingredientes: ['Ácido hialurónico', 'Péptidos', 'SPF 15'],
    rating: 4.7,
    review_count: 1523,
    es_nuevo: true,
    created_at: '2024-06-01T00:00:00Z',
  },
  {
    id: 'p3',
    marca_id: 'm1',
    nombre: 'Legendary Lashes Volume 2 Mascara',
    descripcion: 'Máscara de pestañas con fórmula de fibras que alarga y da volumen extremo. Resistente al agua con vitamina B5.',
    precio_cop: 145000,
    categoria: 'ojos',
    imagen_url: 'https://images.unsplash.com/photo-1631214524020-3c69888fd1c8?w=400&h=400&fit=crop',
    acabado: 'Voluminizador',
    duracion_horas: 12,
    ingredientes: ['Vitamina B5', 'Cera de abejas', 'Fibras de nailon'],
    rating: 4.6,
    review_count: 987,
    es_nuevo: false,
    created_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'p4',
    marca_id: 'm1',
    nombre: 'Filmstar Bronze & Glow',
    descripcion: 'El duo de contorno e iluminador favorito de Hollywood. Esculpe, define y da luz al rostro con pigmentos de oro real.',
    precio_cop: 245000,
    categoria: 'contorno',
    imagen_url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&h=400&fit=crop',
    acabado: 'Satinado',
    ingredientes: ['Pigmentos de oro', 'Aceite de argán', 'Vitamina C'],
    rating: 4.8,
    review_count: 1654,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  // NARS (m2)
  {
    id: 'p5',
    marca_id: 'm2',
    nombre: 'Satin Lip Pencil - Rikugien',
    descripcion: 'Lápiz labial satinado con fórmula cremosa ultra-pigmentada. Hidrata mientras colorea con un acabado lujoso que dura todo el día.',
    precio_cop: 98000,
    categoria: 'labios',
    imagen_url: 'https://images.unsplash.com/photo-1596704017234-0902573e2fa1?w=400&h=400&fit=crop',
    tono: 'Rikugien',
    acabado: 'Satinado',
    duracion_horas: 8,
    ingredientes: ['Vitamina E', 'Manteca de karité', 'Aceite de rosa mosqueta'],
    rating: 4.7,
    review_count: 756,
    es_nuevo: false,
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: 'p6',
    marca_id: 'm2',
    nombre: 'Radiant Creamy Concealer',
    descripcion: 'El corrector más premiado de NARS. Cobertura completa con acabado radiante que no se cuartea ni se asienta en líneas finas.',
    precio_cop: 125000,
    categoria: 'base',
    imagen_url: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop',
    tono: 'Vanilla',
    acabado: 'Radiante',
    duracion_horas: 16,
    ingredientes: ['Ácido hialurónico', 'Vitamina C', 'Extracto de regaliz'],
    rating: 4.9,
    review_count: 3241,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p7',
    marca_id: 'm2',
    nombre: "Climax Extreme Mascara",
    descripcion: 'Máscara de efecto ventilador con fórmula negra intensamente pigmentada. Crea pestañas dramáticas y perfectamente separadas.',
    precio_cop: 108000,
    categoria: 'ojos',
    imagen_url: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=400&h=400&fit=crop',
    acabado: 'Ultra Negro',
    duracion_horas: 10,
    ingredientes: ['Polímeros de relleno', 'Vitamina B5', 'Cera sintética'],
    rating: 4.5,
    review_count: 892,
    es_nuevo: true,
    created_at: '2024-07-01T00:00:00Z',
  },
  {
    id: 'p8',
    marca_id: 'm2',
    nombre: 'Laguna Bronzing Powder',
    descripcion: 'El bronceador que creó NARS. Una mezcla perfecta de tonos bronce dorados para un efecto de playa perfecto todo el año.',
    precio_cop: 148000,
    categoria: 'contorno',
    imagen_url: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop',
    tono: 'Laguna',
    acabado: 'Satinado',
    ingredientes: ['Mica', 'Aceite de jojoba', 'Vitamina E'],
    rating: 4.8,
    review_count: 2156,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  // MAC (m3)
  {
    id: 'p9',
    marca_id: 'm3',
    nombre: 'Retro Matte Lipstick - Ruby Woo',
    descripcion: 'El labial más vendido de MAC. Un rojo intenso con acabado matte retro que se mantiene fijo durante horas. Un clásico de culto.',
    precio_cop: 95000,
    categoria: 'labios',
    imagen_url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop',
    tono: 'Ruby Woo',
    acabado: 'Matte Retro',
    duracion_horas: 6,
    ingredientes: ['Cera de carnauba', 'Vitamina E', 'Aceite de ricino'],
    rating: 4.8,
    review_count: 5621,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p10',
    marca_id: 'm3',
    nombre: 'Studio Fix Fluid SPF 15',
    descripcion: 'Base líquida de cobertura completa con SPF 15. Control de brillo por 8 horas. Disponible en 65 tonos para todas las pieles.',
    precio_cop: 168000,
    categoria: 'base',
    imagen_url: 'https://images.unsplash.com/photo-1512207736890-6ffed8a84e8d?w=400&h=400&fit=crop',
    tono: 'NC25',
    acabado: 'Matte',
    duracion_horas: 8,
    ingredientes: ['SPF 15', 'Dióxido de titanio', 'Polímeros'],
    rating: 4.6,
    review_count: 2341,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p11',
    marca_id: 'm3',
    nombre: 'Prep + Prime Fix+',
    descripcion: 'Spray multiusos que fija el maquillaje, hidrata y refresca la piel. Infundido con vitaminas C, E y negundo. Un esencial de MAC.',
    precio_cop: 118000,
    categoria: 'base',
    imagen_url: 'https://images.unsplash.com/photo-1631214524020-3c69888fd1c8?w=400&h=400&fit=crop',
    acabado: 'Fijador',
    duracion_horas: 12,
    ingredientes: ['Vitamina C', 'Vitamina E', 'Extracto de negundo'],
    rating: 4.7,
    review_count: 1876,
    es_nuevo: false,
    created_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'p12',
    marca_id: 'm3',
    nombre: 'Pro Longwear Paint Pot - Painterly',
    descripcion: 'Sombra en crema de larga duración. Funciona como base de sombras o como color de párpado solo. Pillow Talk de los artistas.',
    precio_cop: 85000,
    categoria: 'ojos',
    imagen_url: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop',
    tono: 'Painterly',
    acabado: 'Crema',
    duracion_horas: 24,
    ingredientes: ['Polímeros de sílicona', 'Mica', 'Cera sintética'],
    rating: 4.8,
    review_count: 987,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  // Fenty Beauty (m4)
  {
    id: 'p13',
    marca_id: 'm4',
    nombre: 'Pro Filt\'r Soft Matte Foundation',
    descripcion: 'La base que cambió todo. 50 tonos para todos los colores de piel. Cobertura buildable con acabado matte que luce real, nunca artificial.',
    precio_cop: 195000,
    categoria: 'base',
    imagen_url: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop',
    tono: '235N',
    acabado: 'Soft Matte',
    duracion_horas: 12,
    ingredientes: ['Agua', 'Dimeticona', 'Dióxido de titanio'],
    rating: 4.7,
    review_count: 8934,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p14',
    marca_id: 'm4',
    nombre: 'Gloss Bomb Universal Lip Luminizer',
    descripcion: 'El gloss favorito de Rihanna. Un brillo labial no pegajoso con reflejo de diamante. El tono Fenty Glow favorece a todos.',
    precio_cop: 115000,
    categoria: 'labios',
    imagen_url: 'https://images.unsplash.com/photo-1586495777744-4e6232bf4400?w=400&h=400&fit=crop',
    tono: 'Fenty Glow',
    acabado: 'Gloss',
    duracion_horas: 4,
    ingredientes: ['Vitamina E', 'Aceite de frambuesa', 'Extracto de vainilla'],
    rating: 4.9,
    review_count: 5432,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p15',
    marca_id: 'm4',
    nombre: 'Killawatt Freestyle Highlighter',
    descripcion: 'Iluminador en polvo con partículas de luz microfinas. Refleja la luz para un glow sobrenatural que se ve increíble en fotos.',
    precio_cop: 155000,
    categoria: 'iluminador',
    imagen_url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&h=400&fit=crop',
    tono: 'Trophy Wife',
    acabado: 'Glitter',
    ingredientes: ['Mica', 'Óxidos de hierro', 'Pigmentos ultramarinos'],
    rating: 4.8,
    review_count: 3210,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p16',
    marca_id: 'm4',
    nombre: 'Cheeks Out Freestyle Cream Bronzer',
    descripcion: 'Bronceador en crema de fácil difuminación. Crea un bronceado natural sin el polvo. Enriquecido con extracto de baobab.',
    precio_cop: 135000,
    categoria: 'contorno',
    imagen_url: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop',
    tono: 'Mocha Mami',
    acabado: 'Crema',
    ingredientes: ['Extracto de baobab', 'Manteca de karité', 'Aceite de jojoba'],
    rating: 4.6,
    review_count: 1543,
    es_nuevo: true,
    created_at: '2024-08-01T00:00:00Z',
  },
  // Dior Beauty (m5)
  {
    id: 'p17',
    marca_id: 'm5',
    nombre: 'Rouge Dior Satin Lipstick - 720 Icône',
    descripcion: 'El labial de lujo por excelencia. Fórmula con extracto de Rosa de Granville, el flor emblemática de Dior. Color rico y cremoso.',
    precio_cop: 248000,
    categoria: 'labios',
    imagen_url: 'https://images.unsplash.com/photo-1586495777744-4e6232bf4400?w=400&h=400&fit=crop',
    tono: '720 Icône',
    acabado: 'Satinado',
    duracion_horas: 8,
    ingredientes: ['Extracto de Rosa Granville', 'Cera de abeja', 'Aceite de jojoba'],
    rating: 4.8,
    review_count: 1234,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p18',
    marca_id: 'm5',
    nombre: 'Dior Forever Skin Glow Foundation',
    descripcion: 'Base líquida con acabado glow natural de larga duración. SPF 35 y fórmula enriquecida con Micellar Water y extractos florales.',
    precio_cop: 345000,
    categoria: 'base',
    imagen_url: 'https://images.unsplash.com/photo-1512207736890-6ffed8a84e8d?w=400&h=400&fit=crop',
    tono: '2N Neutro',
    acabado: 'Glow',
    duracion_horas: 24,
    ingredientes: ['SPF 35', 'Extractos florales', 'Ácido hialurónico'],
    rating: 4.9,
    review_count: 876,
    es_nuevo: true,
    created_at: '2024-09-01T00:00:00Z',
  },
  {
    id: 'p19',
    marca_id: 'm5',
    nombre: 'Diorshow On Stage Liner',
    descripcion: 'Delineador líquido de punta fina ultra-precisa. Negro profundo con fórmula de 24 horas que no se corre ni se descascara.',
    precio_cop: 128000,
    categoria: 'ojos',
    imagen_url: 'https://images.unsplash.com/photo-1631214524020-3c69888fd1c8?w=400&h=400&fit=crop',
    acabado: 'Negro Intenso',
    duracion_horas: 24,
    ingredientes: ['Polímeros acrílicos', 'Pigmento negro', 'Glicerina'],
    rating: 4.7,
    review_count: 543,
    es_nuevo: false,
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: 'p20',
    marca_id: 'm5',
    nombre: 'Dior Backstage Contour Palette',
    descripcion: 'Paleta de contorno profesional con 4 tonos universales. Los mismos usados por los maquilladores en las pasarelas de Dior.',
    precio_cop: 298000,
    categoria: 'contorno',
    imagen_url: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop',
    acabado: 'Polvo',
    ingredientes: ['Mica', 'Óxidos de hierro', 'Talco'],
    rating: 4.6,
    review_count: 765,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  // YSL Beauty (m6)
  {
    id: 'p21',
    marca_id: 'm6',
    nombre: 'Rouge Pur Couture Lipstick - The Bold',
    descripcion: 'Labial de larga duración con cobertura total en un solo desliz. El rojo más audaz de YSL. Fórmula enriquecida con aceite de rosa.',
    precio_cop: 215000,
    categoria: 'labios',
    imagen_url: 'https://images.unsplash.com/photo-1596704017234-0902573e2fa1?w=400&h=400&fit=crop',
    tono: '1966 Rouge Libre',
    acabado: 'Matte',
    duracion_horas: 10,
    ingredientes: ['Aceite de rosa', 'Cera de carnauba', 'Vitamina E'],
    rating: 4.7,
    review_count: 1123,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p22',
    marca_id: 'm6',
    nombre: 'Touche Éclat Blur Primer',
    descripcion: 'El primer paso del ritual YSL. Minimiza poros, suaviza y prepara la piel para una base perfecta. El secreto del glow parisino.',
    precio_cop: 198000,
    categoria: 'base',
    imagen_url: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop',
    acabado: 'Blur',
    duracion_horas: 8,
    ingredientes: ['Sílice', 'Glicerina', 'Extracto de arroz'],
    rating: 4.5,
    review_count: 867,
    es_nuevo: false,
    created_at: '2024-04-01T00:00:00Z',
  },
  {
    id: 'p23',
    marca_id: 'm6',
    nombre: 'Lash Clash Extreme Volume Mascara',
    descripcion: 'Máscara de volumen extremo con cepillo con 36 picos de precisión. Crea un efecto de pestañas postizas desde la primera aplicación.',
    precio_cop: 145000,
    categoria: 'ojos',
    imagen_url: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=400&h=400&fit=crop',
    acabado: 'Volumen Extremo',
    duracion_horas: 12,
    ingredientes: ['Cera de carnauba', 'Polímeros de caucho', 'Vitamina B5'],
    rating: 4.6,
    review_count: 654,
    es_nuevo: true,
    created_at: '2024-07-01T00:00:00Z',
  },
  {
    id: 'p24',
    marca_id: 'm6',
    nombre: 'Or Rouge Anti-Aging Blush',
    descripcion: 'Rubor antiedad formulado con oro coloidal y extracto de Oud. Aporta color y cuidado al mismo tiempo. El lujo en su máxima expresión.',
    precio_cop: 285000,
    categoria: 'contorno',
    imagen_url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&h=400&fit=crop',
    tono: 'Brun Cuivré',
    acabado: 'Satinado',
    ingredientes: ['Oro coloidal', 'Extracto de Oud', 'Vitamina C'],
    rating: 4.8,
    review_count: 432,
    es_nuevo: false,
    created_at: '2024-02-01T00:00:00Z',
  },
  // Rare Beauty (m7)
  {
    id: 'p25',
    marca_id: 'm7',
    nombre: 'Soft Pinch Liquid Blush - Joy',
    descripcion: 'El rubor líquido viral de Selena Gomez. Un poco es suficiente para un flush natural de color. Fórmula de larga duración sin resecamiento.',
    precio_cop: 128000,
    categoria: 'contorno',
    imagen_url: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop',
    tono: 'Joy',
    acabado: 'Líquido',
    duracion_horas: 12,
    ingredientes: ['Agua', 'Glicerina', 'Pigmentos orgánicos'],
    rating: 4.9,
    review_count: 7654,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p26',
    marca_id: 'm7',
    nombre: 'Stay Vulnerable Melting Eyeshadow - Nearly Mauve',
    descripcion: 'Sombra en crema que se funde con la piel para un look de ojos natural y ahumado. Fórmula vegan con aceite de aguacate.',
    precio_cop: 98000,
    categoria: 'ojos',
    imagen_url: 'https://images.unsplash.com/photo-1631214524020-3c69888fd1c8?w=400&h=400&fit=crop',
    tono: 'Nearly Mauve',
    acabado: 'Crema',
    duracion_horas: 8,
    ingredientes: ['Aceite de aguacate', 'Cera de candelilla', 'Mica'],
    rating: 4.7,
    review_count: 1876,
    es_nuevo: true,
    created_at: '2024-08-01T00:00:00Z',
  },
  {
    id: 'p27',
    marca_id: 'm7',
    nombre: 'Positive Light Silky Touch Highlighter',
    descripcion: 'Iluminador en polvo ultrasuave que refleja la luz como un espejo. Pigmentos de alta dimensión para un glow que se ve natural.',
    precio_cop: 115000,
    categoria: 'iluminador',
    imagen_url: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop',
    tono: 'Flushed',
    acabado: 'Polvo',
    ingredientes: ['Mica', 'Perlas de luminosidad', 'Vitamina E'],
    rating: 4.6,
    review_count: 1234,
    es_nuevo: false,
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: 'p28',
    marca_id: 'm7',
    nombre: 'With Gratitude Dewy Lip Balm',
    descripcion: 'Bálsamo labial con tinte de color que hidrata profundamente. Infundido con manteca de karité y extracto de rosa. Perfecto para uso diario.',
    precio_cop: 75000,
    categoria: 'labios',
    imagen_url: 'https://images.unsplash.com/photo-1586495777744-4e6232bf4400?w=400&h=400&fit=crop',
    tono: 'Elated',
    acabado: 'Dewy',
    duracion_horas: 4,
    ingredientes: ['Manteca de karité', 'Extracto de rosa', 'Vitamina E'],
    rating: 4.8,
    review_count: 2345,
    es_nuevo: false,
    created_at: '2024-05-01T00:00:00Z',
  },
  // Huda Beauty (m8)
  {
    id: 'p29',
    marca_id: 'm8',
    nombre: 'Power Bullet Matte Lipstick - Provocateur',
    descripcion: 'Labial matte de ultra-pigmentación con fórmula confort. Color intenso que dura hasta 8 horas sin resecamiento gracias al aceite de argán.',
    precio_cop: 135000,
    categoria: 'labios',
    imagen_url: 'https://images.unsplash.com/photo-1596704017234-0902573e2fa1?w=400&h=400&fit=crop',
    tono: 'Provocateur',
    acabado: 'Matte',
    duracion_horas: 8,
    ingredientes: ['Aceite de argán', 'Vitamina E', 'Cera de carnauba'],
    rating: 4.7,
    review_count: 2156,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p30',
    marca_id: 'm8',
    nombre: '#FauxFilter Foundation - Latte',
    descripcion: 'Base de cobertura total con efecto filtro de Instagram. Fórmula buildable y transfer-proof para una piel impecable todo el día.',
    precio_cop: 215000,
    categoria: 'base',
    imagen_url: 'https://images.unsplash.com/photo-1512207736890-6ffed8a84e8d?w=400&h=400&fit=crop',
    tono: 'Latte',
    acabado: 'Matte',
    duracion_horas: 16,
    ingredientes: ['Dimeticona', 'Dióxido de titanio', 'Sílice'],
    rating: 4.6,
    review_count: 3421,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p31',
    marca_id: 'm8',
    nombre: 'Glowish Multidew Skin Tint',
    descripcion: 'Tinte de piel ligero con SPF 30 para una cobertura sheer luminosa. Enriquecido con extracto de noni y vitamina C para pieles brillantes.',
    precio_cop: 178000,
    categoria: 'base',
    imagen_url: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop',
    tono: '3 Light Sand',
    acabado: 'Luminoso',
    duracion_horas: 10,
    ingredientes: ['SPF 30', 'Extracto de noni', 'Vitamina C'],
    rating: 4.5,
    review_count: 1654,
    es_nuevo: true,
    created_at: '2024-09-01T00:00:00Z',
  },
  {
    id: 'p32',
    marca_id: 'm8',
    nombre: 'Rose Gold Remastered Palette',
    descripcion: 'La paleta icónica de Huda Beauty reformulada. 18 sombras en tonos rose gold, cobre y champán para crear looks desde cotidianos hasta dramáticos.',
    precio_cop: 295000,
    categoria: 'ojos',
    imagen_url: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop',
    acabado: 'Shimmer/Matte',
    ingredientes: ['Mica', 'Talco', 'Aceite de jojoba'],
    rating: 4.9,
    review_count: 4532,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  // Maybelline (m9)
  {
    id: 'p33',
    marca_id: 'm9',
    nombre: 'SuperStay Matte Ink Lipstick - Pioneer',
    descripcion: 'Labial líquido de hasta 16 horas de duración. Fórmula con aceite de argán que se seca a un matte impactante sin resecamiento.',
    precio_cop: 48000,
    categoria: 'labios',
    imagen_url: 'https://images.unsplash.com/photo-1586495777744-4e6232bf4400?w=400&h=400&fit=crop',
    tono: 'Pioneer',
    acabado: 'Matte Ink',
    duracion_horas: 16,
    ingredientes: ['Aceite de argán', 'Vitamina E', 'Polímeros de larga duración'],
    rating: 4.6,
    review_count: 8934,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p34',
    marca_id: 'm9',
    nombre: 'Fit Me Matte + Poreless Foundation',
    descripcion: 'Base líquida que controla el brillo y minimiza poros. Disponible en 40+ tonos. La más vendida de Maybelline en Colombia.',
    precio_cop: 65000,
    categoria: 'base',
    imagen_url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop',
    tono: '220 Natural Beige',
    acabado: 'Matte',
    duracion_horas: 8,
    ingredientes: ['Sílice', 'Dióxido de titanio', 'Polímeros'],
    rating: 4.4,
    review_count: 12456,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p35',
    marca_id: 'm9',
    nombre: 'Lash Sensational Sky High Mascara',
    descripcion: 'La máscara viral de TikTok. Cepillo en forma de C que llega a todas las pestañas para un efecto de abanico dramático.',
    precio_cop: 55000,
    categoria: 'ojos',
    imagen_url: 'https://images.unsplash.com/photo-1631214524020-3c69888fd1c8?w=400&h=400&fit=crop',
    acabado: 'Alargador',
    duracion_horas: 10,
    ingredientes: ['Bambú', 'Aceite de argán', 'Provitamina B5'],
    rating: 4.7,
    review_count: 25678,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p36',
    marca_id: 'm9',
    nombre: 'Master Chrome Highlighter - Molten Rose Gold',
    descripcion: 'Iluminador en polvo prensado con acabado metálico intenso. Un glow dramático para noches especiales o sesiones de fotos.',
    precio_cop: 48000,
    categoria: 'iluminador',
    imagen_url: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=400&h=400&fit=crop',
    tono: 'Molten Rose Gold',
    acabado: 'Metálico',
    ingredientes: ['Mica', 'Polvo de perla', 'Vitamina E'],
    rating: 4.5,
    review_count: 3456,
    es_nuevo: false,
    created_at: '2024-04-01T00:00:00Z',
  },
  // L'Oréal Paris (m10)
  {
    id: 'p37',
    marca_id: 'm10',
    nombre: "Color Riche Satin Lipstick - Beige Sangria",
    descripcion: 'Labial satinado clásico de L\'Oréal con 40 años de historia. Fórmula con aceite de argán marroquí para labios suaves y luminosos.',
    precio_cop: 42000,
    categoria: 'labios',
    imagen_url: 'https://images.unsplash.com/photo-1596704017234-0902573e2fa1?w=400&h=400&fit=crop',
    tono: 'Beige Sangria',
    acabado: 'Satinado',
    duracion_horas: 6,
    ingredientes: ['Aceite de argán', 'Vitamina E', 'Cera de abeja'],
    rating: 4.4,
    review_count: 6754,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p38',
    marca_id: 'm10',
    nombre: 'Infaillible 24H Fresh Wear Foundation',
    descripcion: 'Base de 24 horas de duración que se adapta al calor colombiano. Resistente al calor, sudor y humedad. Cobertura de media a completa.',
    precio_cop: 78000,
    categoria: 'base',
    imagen_url: 'https://images.unsplash.com/photo-1512207736890-6ffed8a84e8d?w=400&h=400&fit=crop',
    tono: '200 Golden Sand',
    acabado: 'Matte',
    duracion_horas: 24,
    ingredientes: ['Polímeros termorresistentes', 'SPF 25', 'Glicerina'],
    rating: 4.5,
    review_count: 9876,
    es_nuevo: false,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'p39',
    marca_id: 'm10',
    nombre: 'Paradise Enchanted Fruit-Scented Blush',
    descripcion: 'Rubor en polvo con aroma a frutas tropicales. Los pigmentos ligeros crean un color de mejillas natural y juvenil. Perfecto para el clima colombiano.',
    precio_cop: 58000,
    categoria: 'contorno',
    imagen_url: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=400&h=400&fit=crop',
    tono: 'Peach Adagio',
    acabado: 'Polvo',
    ingredientes: ['Talco', 'Mica', 'Fragancias frutales naturales'],
    rating: 4.3,
    review_count: 2345,
    es_nuevo: true,
    created_at: '2024-10-01T00:00:00Z',
  },
  {
    id: 'p40',
    marca_id: 'm10',
    nombre: 'True Match Super Blendable Concealer',
    descripcion: 'Corrector con 45 tonos para una cobertura perfecta que se fusiona con tu piel. Fórmula antiojeras con extracto de rosa blanca.',
    precio_cop: 52000,
    categoria: 'base',
    imagen_url: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop',
    tono: 'W3 Warm Light',
    acabado: 'Natural',
    duracion_horas: 12,
    ingredientes: ['Extracto de rosa blanca', 'Ácido hialurónico', 'Vitamina C'],
    rating: 4.5,
    review_count: 4567,
    es_nuevo: false,
    created_at: '2024-02-01T00:00:00Z',
  },
]

// Add marca data to products
PRODUCTOS.forEach(producto => {
  producto.marca = MARCAS.find(m => m.id === producto.marca_id)
})

export const GALERIA_ITEMS: GaleriaItem[] = [
  {
    id: 'g1',
    usuario_nombre: 'Valentina Rodríguez',
    usuario_ig: '@vale.beauty.col',
    foto_url: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=600&h=800&fit=crop',
    producto_id: 'p1',
    descripcion_look: 'Look de noche con Pillow Talk de Charlotte Tilbury 💋 Perfectamente complementado con delineado cat-eye',
    likes: 234,
    aprobada: true,
    created_at: '2024-10-15T14:30:00Z',
  },
  {
    id: 'g2',
    usuario_nombre: 'Isabela Martínez',
    usuario_ig: '@isabelamakeup',
    foto_url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&h=900&fit=crop',
    producto_id: 'p13',
    descripcion_look: 'Piel glass con Fenty Pro Filt\'r + highlighter Trophy Wife. El mejor dúo! ✨',
    likes: 456,
    aprobada: true,
    created_at: '2024-10-12T10:00:00Z',
  },
  {
    id: 'g3',
    usuario_nombre: 'Camila Sánchez',
    usuario_ig: '@camila.glam',
    foto_url: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&h=700&fit=crop',
    producto_id: 'p9',
    descripcion_look: 'Red lip classic con MAC Ruby Woo y skin natural. El rojo perfecto para toda ocasión 🔴',
    likes: 678,
    aprobada: true,
    created_at: '2024-10-10T16:45:00Z',
  },
  {
    id: 'g4',
    usuario_nombre: 'Sofía Herrera',
    foto_url: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&h=800&fit=crop',
    producto_id: 'p25',
    descripcion_look: 'Soft girl era con Rare Beauty blush en Joy 🌸 Un poco va muy lejos!',
    likes: 892,
    aprobada: true,
    created_at: '2024-10-08T09:20:00Z',
  },
  {
    id: 'g5',
    usuario_nombre: 'Mariana López',
    usuario_ig: '@marilopez.mua',
    foto_url: 'https://images.unsplash.com/photo-1512207736890-6ffed8a84e8d?w=600&h=900&fit=crop',
    producto_id: 'p17',
    descripcion_look: 'Rouge Dior 720 Icône para una boda en Cartagena ☀️ La base Dior Forever duraó todo el día!',
    likes: 543,
    aprobada: true,
    created_at: '2024-10-05T20:00:00Z',
  },
  {
    id: 'g6',
    usuario_nombre: 'Daniela Castro',
    usuario_ig: '@dani.beautyco',
    foto_url: 'https://images.unsplash.com/photo-1631214524020-3c69888fd1c8?w=600&h=700&fit=crop',
    producto_id: 'p6',
    descripcion_look: 'Corrector NARS en Vanilla para un fresh face look. La cobertura es increíble sin sentirse pesado ⭐',
    likes: 321,
    aprobada: true,
    created_at: '2024-10-03T11:15:00Z',
  },
  {
    id: 'g7',
    usuario_nombre: 'Alejandra Gómez',
    usuario_ig: '@alejandra.glam',
    foto_url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&h=850&fit=crop',
    producto_id: 'p15',
    descripcion_look: 'Glow de la temporada con Fenty Killawatt en Trophy Wife 🥇 Para sesión de fotos en Medellín',
    likes: 765,
    aprobada: true,
    created_at: '2024-09-28T14:00:00Z',
  },
  {
    id: 'g8',
    usuario_nombre: 'Natalia Pérez',
    usuario_ig: '@nati.beauty',
    foto_url: 'https://images.unsplash.com/photo-1596704017234-0902573e2fa1?w=600&h=800&fit=crop',
    producto_id: 'p21',
    descripcion_look: 'YSL Rouge Pur Couture para una noche en Bogotá 🌃 El labial más audaz que he usado en mi vida',
    likes: 987,
    aprobada: true,
    created_at: '2024-09-25T21:30:00Z',
  },
  {
    id: 'g9',
    usuario_nombre: 'Carolina Jiménez',
    usuario_ig: '@caro.makeupbog',
    foto_url: 'https://images.unsplash.com/photo-1586495777744-4e6232bf4400?w=600&h=900&fit=crop',
    producto_id: 'p32',
    descripcion_look: 'Paleta Rose Gold de Huda Beauty para un quince años. Las clientas quedaron enamoradas! ✨',
    likes: 1234,
    aprobada: true,
    created_at: '2024-09-20T15:45:00Z',
  },
  {
    id: 'g10',
    usuario_nombre: 'Paulina Vargas',
    foto_url: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=600&h=750&fit=crop',
    producto_id: 'p35',
    descripcion_look: 'Sky High Mascara de Maybelline para mis pestañas naturales 😍 El precio no puede ser más justo!',
    likes: 445,
    aprobada: true,
    created_at: '2024-09-18T08:00:00Z',
  },
  {
    id: 'g11',
    usuario_nombre: 'Juliana Moreno',
    usuario_ig: '@juli.beauty.col',
    foto_url: 'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=600&h=800&fit=crop',
    producto_id: 'p26',
    descripcion_look: 'Sombra cremosa Rare Beauty en Nearly Mauve para un look de día romantico 🌸',
    likes: 567,
    aprobada: false,
    created_at: '2024-10-16T12:00:00Z',
  },
  {
    id: 'g12',
    usuario_nombre: 'Andrea Quintero',
    usuario_ig: '@andrea.mua.bogota',
    foto_url: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&h=900&fit=crop',
    producto_id: 'p4',
    descripcion_look: 'Filmstar Bronze & Glow de Charlotte Tilbury para un look de editorial. El bronzeado perfecto! 🌟',
    likes: 876,
    aprobada: false,
    created_at: '2024-10-17T09:30:00Z',
  },
]

export const SUGERENCIAS: Sugerencia[] = [
  {
    id: 's1',
    nombre: 'Laura Medina',
    email: 'laura@gmail.com',
    categoria: 'producto',
    mensaje: 'Sería increíble tener productos de Rhode Skin! La línea de hidratación de Hailey Bieber es perfecta para el clima de Bogotá.',
    votos: 45,
    estado: 'en_proceso',
    nota_interna: 'Contactar distribuidor Rhode Colombia',
    created_at: '2024-10-10T10:00:00Z',
  },
  {
    id: 's2',
    nombre: 'María Fernanda',
    categoria: 'descuento',
    mensaje: 'Una tarjeta de cliente frecuente o descuento de cumpleaños sería maravilloso. Compro aquí todos los meses!',
    votos: 38,
    estado: 'vista',
    created_at: '2024-10-08T14:30:00Z',
  },
  {
    id: 's3',
    nombre: 'Valentina',
    email: 'vale@hotmail.com',
    categoria: 'producto',
    mensaje: 'Por favor traigan la paleta de sombras Naked de Urban Decay. Es imposible conseguirla en Colombia.',
    votos: 67,
    estado: 'nueva',
    created_at: '2024-10-15T09:00:00Z',
  },
  {
    id: 's4',
    categoria: 'servicio',
    mensaje: 'Estaría genial tener videos tutoriales de YouTube con los productos. Ayudaría mucho a elegir colores.',
    votos: 29,
    estado: 'nueva',
    created_at: '2024-10-14T16:00:00Z',
  },
  {
    id: 's5',
    nombre: 'Daniela Castro',
    email: 'daniela.c@gmail.com',
    categoria: 'descuento',
    mensaje: 'Un descuento por primera compra del 15% sería increíble para atraer nuevas clientas. Yo traería a mis amigas!',
    votos: 54,
    estado: 'agregada',
    nota_interna: 'Implementar con código PRIMERA15',
    created_at: '2024-09-20T11:00:00Z',
  },
  {
    id: 's6',
    nombre: 'Sofía R.',
    categoria: 'producto',
    mensaje: 'Necesitamos más opciones de base para piel oscura tipo NC45-NC50. Fenty tiene pero queremos más marcas.',
    votos: 41,
    estado: 'vista',
    created_at: '2024-10-05T13:00:00Z',
  },
  {
    id: 's7',
    categoria: 'servicio',
    mensaje: 'Sería útil tener un quiz de tipo de piel en el sitio web para recomendar productos automáticamente.',
    votos: 33,
    estado: 'nueva',
    created_at: '2024-10-13T10:30:00Z',
  },
  {
    id: 's8',
    nombre: 'Camila Torres',
    email: 'camila.torres@yahoo.com',
    categoria: 'producto',
    mensaje: 'Por favor incluyan Glossier! Sus productos son perfectos para piel sensible como la mía.',
    votos: 48,
    estado: 'en_proceso',
    nota_interna: 'Glossier no tiene distribución en Colombia aún',
    created_at: '2024-09-28T15:00:00Z',
  },
]

export const PEDIDOS: Pedido[] = [
  {
    id: 'ord-001',
    cliente_nombre: 'Ana María Rodríguez',
    cliente_tel: '+57 3001234567',
    cliente_email: 'anamaria@gmail.com',
    cliente_ciudad: 'Bogotá',
    direccion: 'Cra 15 # 93-47 Apto 502, Chicó',
    metodo_pago: 'Nequi',
    productos: [
      { producto_id: 'p1', nombre: 'Matte Revolution Lipstick - Pillow Talk', precio_cop: 165000, cantidad: 1, tono: 'Pillow Talk' },
      { producto_id: 'p6', nombre: 'Radiant Creamy Concealer', precio_cop: 125000, cantidad: 1, tono: 'Vanilla' },
    ],
    total_cop: 290000,
    estado: 'entregado',
    wa_enviado: true,
    created_at: '2024-10-10T09:00:00Z',
  },
  {
    id: 'ord-002',
    cliente_nombre: 'Valentina Gómez',
    cliente_tel: '+57 3109876543',
    cliente_ciudad: 'Medellín',
    direccion: 'El Poblado, Calle 10 # 43C-24',
    metodo_pago: 'Bancolombia',
    productos: [
      { producto_id: 'p13', nombre: "Pro Filt'r Soft Matte Foundation", precio_cop: 195000, cantidad: 1, tono: '235N' },
      { producto_id: 'p15', nombre: 'Killawatt Freestyle Highlighter', precio_cop: 155000, cantidad: 1, tono: 'Trophy Wife' },
    ],
    total_cop: 350000,
    estado: 'enviado',
    wa_enviado: true,
    created_at: '2024-10-12T14:30:00Z',
  },
  {
    id: 'ord-003',
    cliente_nombre: 'Isabela Martínez',
    cliente_tel: '+57 3205554433',
    cliente_email: 'isabela.m@hotmail.com',
    cliente_ciudad: 'Cali',
    direccion: 'Ciudad Jardín, Cra 100 # 11-60',
    metodo_pago: 'Daviplata',
    productos: [
      { producto_id: 'p32', nombre: 'Rose Gold Remastered Palette', precio_cop: 295000, cantidad: 1 },
    ],
    total_cop: 295000,
    estado: 'confirmado',
    wa_enviado: true,
    created_at: '2024-10-14T11:00:00Z',
  },
  {
    id: 'ord-004',
    cliente_nombre: 'Camila Sánchez',
    cliente_tel: '+57 3156667788',
    cliente_ciudad: 'Barranquilla',
    direccion: 'Altos del Prado, Calle 76 # 51B-131',
    metodo_pago: 'Nequi',
    productos: [
      { producto_id: 'p9', nombre: 'Retro Matte Lipstick - Ruby Woo', precio_cop: 95000, cantidad: 2, tono: 'Ruby Woo' },
    ],
    total_cop: 190000,
    estado: 'nuevo',
    wa_enviado: false,
    created_at: '2024-10-16T16:00:00Z',
  },
  {
    id: 'ord-005',
    cliente_nombre: 'Sofía Herrera',
    cliente_tel: '+57 3001112233',
    cliente_email: 'sofia.h@gmail.com',
    cliente_ciudad: 'Bogotá',
    direccion: 'Chapinero Alto, Cra 7 # 69-31',
    metodo_pago: 'Efectivo',
    productos: [
      { producto_id: 'p25', nombre: 'Soft Pinch Liquid Blush - Joy', precio_cop: 128000, cantidad: 1, tono: 'Joy' },
      { producto_id: 'p27', nombre: 'Positive Light Silky Touch Highlighter', precio_cop: 115000, cantidad: 1, tono: 'Flushed' },
      { producto_id: 'p28', nombre: 'With Gratitude Dewy Lip Balm', precio_cop: 75000, cantidad: 1, tono: 'Elated' },
    ],
    total_cop: 318000,
    estado: 'entregado',
    notas: 'Por favor empacar con papel de regalo para regalo de cumpleaños',
    wa_enviado: true,
    created_at: '2024-10-08T10:30:00Z',
  },
  {
    id: 'ord-006',
    cliente_nombre: 'Mariana López',
    cliente_tel: '+57 3204445566',
    cliente_ciudad: 'Cartagena',
    direccion: 'Bocagrande, Av. San Martín # 7-69',
    metodo_pago: 'Bancolombia',
    productos: [
      { producto_id: 'p17', nombre: 'Rouge Dior Satin Lipstick - 720 Icône', precio_cop: 248000, cantidad: 1, tono: '720 Icône' },
      { producto_id: 'p18', nombre: 'Dior Forever Skin Glow Foundation', precio_cop: 345000, cantidad: 1, tono: '2N Neutro' },
    ],
    total_cop: 593000,
    estado: 'entregado',
    wa_enviado: true,
    created_at: '2024-10-05T12:00:00Z',
  },
  {
    id: 'ord-007',
    cliente_nombre: 'Daniela Castro',
    cliente_tel: '+57 3177778899',
    cliente_email: 'dani.c@gmail.com',
    cliente_ciudad: 'Bogotá',
    direccion: 'Usaquén, Calle 119 # 6-56',
    metodo_pago: 'Nequi',
    productos: [
      { producto_id: 'p21', nombre: 'Rouge Pur Couture Lipstick - The Bold', precio_cop: 215000, cantidad: 1, tono: '1966 Rouge Libre' },
    ],
    total_cop: 215000,
    estado: 'enviado',
    wa_enviado: true,
    created_at: '2024-10-13T17:00:00Z',
  },
  {
    id: 'ord-008',
    cliente_nombre: 'Alejandra Morales',
    cliente_tel: '+57 3050001111',
    cliente_ciudad: 'Pereira',
    direccion: 'Pinares, Cra 20 # 17-50 Casa 5',
    metodo_pago: 'Daviplata',
    productos: [
      { producto_id: 'p33', nombre: 'SuperStay Matte Ink Lipstick - Pioneer', precio_cop: 48000, cantidad: 3, tono: 'Pioneer' },
      { producto_id: 'p35', nombre: 'Lash Sensational Sky High Mascara', precio_cop: 55000, cantidad: 2 },
    ],
    total_cop: 254000,
    estado: 'confirmado',
    wa_enviado: true,
    created_at: '2024-10-15T08:00:00Z',
  },
  {
    id: 'ord-009',
    cliente_nombre: 'Natalia Vargas',
    cliente_tel: '+57 3162223344',
    cliente_ciudad: 'Manizales',
    direccion: 'Cable, Cra 23 # 63-40 Apto 801',
    metodo_pago: 'Efectivo',
    productos: [
      { producto_id: 'p2', nombre: 'Beautiful Skin Foundation', precio_cop: 285000, cantidad: 1, tono: 'N4 Neutral' },
    ],
    total_cop: 285000,
    estado: 'nuevo',
    wa_enviado: false,
    notas: 'Prefiero tono más claro si es posible',
    created_at: '2024-10-17T06:00:00Z',
  },
  {
    id: 'ord-010',
    cliente_nombre: 'Paula Jiménez',
    cliente_tel: '+57 3133334455',
    cliente_email: 'paula.j@outlook.com',
    cliente_ciudad: 'Bogotá',
    direccion: 'Santa Bárbara, Calle 116 # 16-32',
    metodo_pago: 'Nequi',
    productos: [
      { producto_id: 'p14', nombre: 'Gloss Bomb Universal Lip Luminizer', precio_cop: 115000, cantidad: 2, tono: 'Fenty Glow' },
      { producto_id: 'p16', nombre: 'Cheeks Out Freestyle Cream Bronzer', precio_cop: 135000, cantidad: 1, tono: 'Mocha Mami' },
    ],
    total_cop: 365000,
    estado: 'entregado',
    wa_enviado: true,
    created_at: '2024-09-30T14:00:00Z',
  },
  {
    id: 'ord-011',
    cliente_nombre: 'Juliana Ríos',
    cliente_tel: '+57 3015556677',
    cliente_ciudad: 'Bucaramanga',
    direccion: 'Cabecera del Llano, Calle 52 # 39-20',
    metodo_pago: 'Bancolombia',
    productos: [
      { producto_id: 'p29', nombre: 'Power Bullet Matte Lipstick - Provocateur', precio_cop: 135000, cantidad: 1, tono: 'Provocateur' },
      { producto_id: 'p30', nombre: '#FauxFilter Foundation - Latte', precio_cop: 215000, cantidad: 1, tono: 'Latte' },
    ],
    total_cop: 350000,
    estado: 'enviado',
    wa_enviado: true,
    created_at: '2024-10-11T11:30:00Z',
  },
  {
    id: 'ord-012',
    cliente_nombre: 'Luciana Herrera',
    cliente_tel: '+57 3117778899',
    cliente_ciudad: 'Cúcuta',
    direccion: 'La Riviera, Cra 0 E # 7N-20',
    metodo_pago: 'Nequi',
    productos: [
      { producto_id: 'p37', nombre: 'Color Riche Satin Lipstick - Beige Sangria', precio_cop: 42000, cantidad: 2, tono: 'Beige Sangria' },
      { producto_id: 'p38', nombre: 'Infaillible 24H Fresh Wear Foundation', precio_cop: 78000, cantidad: 1, tono: '200 Golden Sand' },
      { producto_id: 'p40', nombre: 'True Match Super Blendable Concealer', precio_cop: 52000, cantidad: 1, tono: 'W3 Warm Light' },
    ],
    total_cop: 214000,
    estado: 'nuevo',
    wa_enviado: false,
    created_at: '2024-10-17T08:30:00Z',
  },
  {
    id: 'ord-013',
    cliente_nombre: 'Catalina Reyes',
    cliente_tel: '+57 3188889900',
    cliente_email: 'catareyes@gmail.com',
    cliente_ciudad: 'Armenia',
    direccion: 'Centenario, Cra 19 # 5-34',
    metodo_pago: 'Daviplata',
    productos: [
      { producto_id: 'p5', nombre: 'Satin Lip Pencil - Rikugien', precio_cop: 98000, cantidad: 1, tono: 'Rikugien' },
    ],
    total_cop: 98000,
    estado: 'confirmado',
    wa_enviado: true,
    created_at: '2024-10-14T09:00:00Z',
  },
  {
    id: 'ord-014',
    cliente_nombre: 'Melissa Salcedo',
    cliente_tel: '+57 3052221133',
    cliente_ciudad: 'Ibagué',
    direccion: 'El Jordán, Calle 60 # 2-98 Casa 12',
    metodo_pago: 'Efectivo',
    productos: [
      { producto_id: 'p34', nombre: 'Fit Me Matte + Poreless Foundation', precio_cop: 65000, cantidad: 1, tono: '220 Natural Beige' },
      { producto_id: 'p36', nombre: 'Master Chrome Highlighter - Molten Rose Gold', precio_cop: 48000, cantidad: 1, tono: 'Molten Rose Gold' },
    ],
    total_cop: 113000,
    estado: 'entregado',
    wa_enviado: true,
    created_at: '2024-10-07T15:00:00Z',
  },
  {
    id: 'ord-015',
    cliente_nombre: 'Xiomara Patiño',
    cliente_tel: '+57 3199990011',
    cliente_email: 'xio.patino@gmail.com',
    cliente_ciudad: 'Santa Marta',
    direccion: 'El Rodadero, Cra 2 # 15-42 Apto 301',
    metodo_pago: 'Nequi',
    productos: [
      { producto_id: 'p24', nombre: 'Or Rouge Anti-Aging Blush', precio_cop: 285000, cantidad: 1, tono: 'Brun Cuivré' },
      { producto_id: 'p23', nombre: 'Lash Clash Extreme Volume Mascara', precio_cop: 145000, cantidad: 1 },
    ],
    total_cop: 430000,
    estado: 'enviado',
    wa_enviado: true,
    created_at: '2024-10-09T13:00:00Z',
  },
]
